server:
  port: 8080

camunda:
  bpm:
    admin-user:
      id: admin
      password: 123
    webapp:
      index-redirect-enabled: true
    filter:
      create: all
    authorization:
      enabled: true
    database:
      type: h2
      schema-update: true

spring:
  mvc:
    cors:
      allowed-origins: "http://localhost:8081"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true